
version: 2

models:
    - name: cust_detail
      description: "customer personal details"
      columns:
          - name: Cust_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: loan_dt
      description: "Loan details"
      columns:
          - name: Loan_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

