version: 2

models:
  - name: active_emp
    description: This table contains active employee data
    columns:
      - name: emp_id
        tests:
          - unique
          - not_null


sources:
  - name: ORGANIZATION
    tables:
      - name: RAW_EMP